site_name: TeraHz Documentation
theme: readthedocs
nav:
- Start page: 'index.md'
- Building manually:
  - Build guide: 'build.md'
  - Latest dependencies: 'dependencies.md'
- Expert's guide:
  - Electrical connections: 'electrical.md'
